import { EmergencyContact } from "../types";
import { COLORS } from "./theme";

export const EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: "amb-108",
    nameKey: "ambulance108",
    number: "108",
    descKey: "ambulanceDesc",
    icon: "medical-bag",
    accent: COLORS.danger,
    badge: "24/7 FREE",
    canSms: true,
  },
  {
    id: "health-104",
    nameKey: "healthHelpline104",
    number: "104",
    descKey: "healthHelplineDesc",
    icon: "phone-classic",
    accent: COLORS.primary,
    badge: "TN GOVT",
    canSms: false,
  },
  {
    id: "police-100",
    nameKey: "police100",
    number: "100",
    descKey: "policeDesc",
    icon: "shield-alert",
    accent: "#1e3a8a",
    badge: "POLICE",
    canSms: true,
  },
  {
    id: "fire-101",
    nameKey: "fire101",
    number: "101",
    descKey: "fireDesc",
    icon: "fire",
    accent: "#ea580c",
    badge: "RESCUE",
    canSms: false,
  },
  {
    id: "women-1091",
    nameKey: "women1091",
    number: "1091",
    descKey: "womenDesc",
    icon: "human-female",
    accent: "#9333ea",
    badge: "HELPLINE",
    canSms: true,
  },
  {
    id: "child-1098",
    nameKey: "child1098",
    number: "1098",
    descKey: "childDesc",
    icon: "baby-face-outline",
    accent: "#0284c7",
    badge: "CHILDLINE",
    canSms: false,
  },
];
